std_msgs/Header header
std_msgs/Int8 id
std_msgs/Int8 mode
geometry_msgs/Pose camera_pose
visualization_msgs/MarkerArray markers
---
bool success
sensor_msgs/PointCloud2 pointcloud_map
---
float64 feedback
